#!/bin/bash

echo "==> Starting pre commit hook"

# Check if there are changes in the /app directory
if git diff --cached --name-only | grep -q "^app/"; then
    # Define the path to the virtual environment
    echo "==> Creating virtual env"
    VENV_DIR=/tmp/pre_commit_venv
    python3 -m venv "$VENV_DIR"
    source "$VENV_DIR/bin/activate"
    pip install --no-cache-dir -q -r requirements.txt
    echo "==> Created virtual env"
    echo "==> Changes in app/ staged"
    # Change directory to /app
    cd app || exit

    # Run pytest tests in the testing/ directory
    pytest testing/

    # Check the exit status of pytest
    if [ $? -ne 0 ]; then
        echo "==> Tests failed. Please fix the failing tests before committing."
        # Deactivate the virtual environment
        deactivate
        # Remove the virtual environment
        rm -rf "$VENV_DIR"
        exit 1  # Stop the commit
    fi
else
    echo "==> No changes in app/ staged. Skipping tests."
fi

# Deactivate the virtual environment
deactivate

# Remove the virtual environment
rm -rf "$VENV_DIR"

# If all tests pass or no changes in /app, allow the commit to proceed
exit 0
